config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "krakes#index"

  resources :entries
  resources :keywords
  resources :krakes do
    member do
      get 'add_approval'
    end
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  # Entry types
  # 1: Best-entry
  # 2: Approval entry
  # 3: Individual entry
  # 4: Entry request

  belongs_to :krake
  validates :description, presence: true
  validates :url, :format => URI::regexp(%w(http https)), unless: :url_empty?

  scope :best,         -> { where(entry_type: 1).last }
  scope :approved,     -> { where(entry_type: 2) }
  scope :disagreed,    -> { where(entry_type: 3) }
  scope :requested,    -> { where(entry_type: 4) }
  scope :user_created, -> { where(entry_type: [1, 3]) }
  scope :non_best,     -> { where(entry_type: [2, 3]) }
  
  def url_empty?
    self.url.nil? || self.url.empty? ? true : false
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def create
    keyword_ids = []
    current_keywords = params[:entry][:current_keywords].split
    k0 = current_keywords.first
    if params[:entry][:disapproval] == "true"
      krake = Krake.find(params[:entry][:krake_id].to_i)
      new_entry = krake.entries.new
      new_entry.user_id = current_user.id
      new_entry.description = params[:entry][:description]
      new_entry.url = params[:entry][:url]
      new_entry.entry_type = 3
      if new_entry.save
        current_keywords.shift
        k = current_keywords
        k.count > 0 ? k = k.join("+") : k = ""
        approved_entry = krake.entries.where(entry_type: 2,
                                             user_id: current_user.id).last
        if !approved_entry.nil?
          approved_entry.destroy
        end
        redirect_to krakes_path(k0: k0, k: k)
        return
      else
        flash[:error] = new_entry.errors.full_messages
        redirect_to krakes_path(k0: k0,
                                k: k, 
                                description: params[:entry][:description], 
                                url: params[:entry][:url])
      end
    else
      # Create keyword if it doesn't exist yet
      if Keyword.find_by_description(k0).nil?
        Keyword.create!(description: k0.downcase)
      end
      keyword_ids << Keyword.find_by_description(k0).id
      current_keywords.shift
      k = ""
      current_keywords.each do |c|
        # Create keyword if it doesn't exist
        if Keyword.find_by_description(c).nil?
          Keyword.create!(description: c.downcase)
          keyword_ids << Keyword.find_by_description(c).id
        else
          if c.length > 0
            keyword_ids << Keyword.find_by_description(c).id
          end
        end
        k += c
        k += "+"
      end
      # Create Krake
      keyword_ids.sort!
      Krake.transaction do
        begin
          krake = Krake.find_by_keyword_ids("+" + keyword_ids.join("+") + "+")
          if krake.nil?
            krake = Krake.create(keyword_ids: "+" + keyword_ids.join("+") + "+")
          end
          @entry = krake.entries.new
          @entry.user_id = current_user.id
          if params[:commit].first(7) == "REQUEST"
            @entry.description = "request"
            @entry.url = ""
            @entry.entry_type = 4
            flash[:notice] = "Your request was saved."
          else
            @entry.description = params[:entry][:description]
            @entry.url = params[:entry][:url]
            @entry.entry_type = 1
          end
          @entry.save!
          redirect_to krakes_path(k0: k0, k: k)
          return
        rescue
          flash[:error] = @entry.errors.full_messages
          redirect_to krakes_path(k0: k0, k: k,
                                  description: params[:entry][:description],
                                  url: params[:entry][:url])
        end
        raise ActiveRecord::Rollback
        redirect_to :back
      end
    end
  end

  def update
    current_keywords = params[:entry][:current_keywords].split
    k0 = current_keywords.first
    current_keywords.shift
    k = current_keywords
    k.count > 0 ? k = k.join("+") : k = ""
    @entry = Entry.find(params[:id])
    @entry.description = params[:entry][:description]
    @entry.url = params[:entry][:url]
    if @entry.save
      redirect_to krakes_path(k0: k0, k: k)
    else
      flash[:error] = @entry.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    if !params[:k0].nil? || !params[:k].nil?
      current_keywords = params[:k].split
      k = current_keywords
      k.count > 0 ? k = k.join("+") : k = ""
      @entry = Entry.find(params[:id])
      @entry.destroy
      if @entry.entry_type == 1 && @entry.krake.entries.non_best.count > 0
        @entry.krake.entries.non_best.first.update(entry_type: 1)
      end
      redirect_to krakes_path(k0: params[:k0], k: k)
    else
      @entry = Entry.find(params[:id])
      @entry.destroy
      if @entry.entry_type == 1 && @entry.krake.entries.non_best.count > 0
        @entry.krake.entries.non_best.first.update(entry_type: 1)
      end
      redirect_to :root
    end
  end
end

app/views/entries/_edit_best_entry.html.erb
<div class="edit-best-entry hidden">
  <h2>Edit entry</h2>
  <%= simple_form_for @best_entry do |f| %>
    <%= f.hidden_field :current_keywords, value: @current_keywords %>
    <%= f.input :description,
                label: "DESCRIPTION",
                label_html: { class: "form-label" },
                input_html: { class: "input-description", rows: 1, maxlength: 50 } %>
    <%= f.input :url,
                label: "URL",
                label_html: { class: "form-label" },
                input_html: { class: "input-url", rows: 1 } %>
    <%= link_to "CANCEL", "#", class: "btn btn-primary", id: "edit-entry-cancel-btn" %>
    <%= f.button :submit, "UPDATE ENTRY", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/entries/_edit_entry.html.erb
<div class="edit-entry hidden">
  <h2>Edit entry</h2>
  <%= simple_form_for @own_entry do |f| %>
    <%= f.hidden_field :current_keywords, value: @current_keywords %>
    <%= f.input :description,
                label: "DESCRIPTION",
                label_html: { class: "form-label" },
                input_html: { class: "input-description", rows: 1, maxlength: 50 } %>
    <%= f.input :url,
                label: "URL",
                label_html: { class: "form-label" },
                input_html: { class: "input-url", rows: 1 } %>
    <%= link_to "CANCEL", "#", class: "btn btn-primary", id: "edit-entry-cancel-btn" %>
    <%= f.button :submit, "UPDATE ENTRY", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/entries/_entry_actions.html.erb
<div class="entry-actions">
  <hr>
  <% if !@own_entry.nil? %>
    <%= link_to "DELETE", entry_path(@own_entry, k0: params[:k0], k: params[:k]), method: :delete, class: "btn btn-primary" %>
    <%= link_to "EDIT", "#", class: "btn btn-primary", id: "edit-entry-btn" %>
  <% else %>
    <% if user_signed_in? && @approved_entry.nil? && @best_entry.user_id != current_user.id %>
      <%= link_to "APPROVE", add_approval_krake_path(@existing_krake, keywords: @current_keywords), class: "btn btn-primary" %>
    <% else %>
      <% if user_signed_in? %>
        <% if @best_entry.user_id == current_user.id %>
          <button class="btn btn-status">YOU APPROVED (CREATED)</button>
          <%= link_to "DELETE", entry_path(@best_entry, k0: params[:k0], k: params[:k]), method: :delete, class: "btn btn-primary" %>
          <%= link_to "EDIT", "#", class: "btn btn-primary", id: "edit-best-entry-btn" %>
        <% else %>
          <button class="btn btn-status">YOU APPROVED</button>
        <% end %>
      <% else %>
        <%= link_to "APPROVE", "#login", data: { toggle: "modal" }, class: "btn btn-primary" %>
      <% end %>
    <% end %>
    <%= link_to "DISAPPROVE", "#", class: "btn btn-primary", id: "disagree-btn" %>
  <% end %>
</div>

app/views/entries/_new_entry.html.erb
<div class="new-entry hidden">
  <h2>Create a new entry</h2>
  <p class="explainer-text">
    Add a short description (name, product, place etc.) and a link which you think is the best resource for these keywords. Help others to get the best and eliminate the agony of choice in the age of information overload.
  </p>
  <%= simple_form_for Entry.new do |f| %>
    <%= f.hidden_field :current_keywords, value: @current_keywords %>
    <%= f.hidden_field :disapproval, value: true %>
    <%= f.hidden_field :krake_id, value: @existing_krake.id %>
    <%= f.input :description,
                label: "DESCRIPTION",
                label_html: { class: "form-label" },
                input_html: { class: "input-description", rows: 1, maxlength: 50, value: params[:description] } %>
    <%= f.input :url,
                label: "URL",
                label_html: { class: "form-label" },
                input_html: { class: "input-url", rows: 1, value: params[:url] } %>
    <% if user_signed_in? %>
      <%= link_to "CANCEL", "#", class: "btn btn-primary", id: "new-entry-cancel-btn" %>
      <%= f.button :submit, "CREATE ENTRY", class: "btn btn-primary" %>
    <% else %>
      <p class="explainer-text">
        Please <%= link_to "login", "#login", data: { toggle: "modal" } %> or <%= link_to "sign up", "#sign_up", data: { toggle: "modal" } %> to create an entry or go <%= link_to "back", "#", id: "new-entry-cancel-btn" %>.
      </p>
    <% end %>
  <% end %>
</div>