config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "krakes#index"

  resources :entries
  resources :keywords
  resources :krakes do
    member do
      get 'add_approval'
    end
  end

end

app/views/layouts/_flash_messages.html.erb
<% if !flash[:error].nil? %>
  <% if !flash.empty? %>
    <% flash.each do |key, value| %>
      <% if value.class == String %>
        <%= content_tag :div, value, class: "flash #{key}" %>
      <% else %>
        <% Array.new(value).each do |elem| %>
            <div id="flash_message" class="alert alert-danger">
              <%= elem %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </p>
<% end %>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="login">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">x</button>
        <h2>login</h2>
      </div>

      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div>
            <%= f.input :login,
                        autofocus: true,
                        label: "USERNAME or EMAIL",
                        label_html: { class: "form-label" } %>
          </div>
          <div>
            <%= f.input :password,
                        autocomplete: "off", 
                        label: "PASSWORD",
                        label_html: { class: "form-label" } %>
          </div>
          <% if devise_mapping.rememberable? -%>
            <div>
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me, class: "form-label" %>
            </div>
          <% end %>
          <br>
          <div>
            <%= f.submit "LOGIN", class:  "btn btn-primary" %>
          </div>
        <% end %>
      </div>

      <div class="modal-footer">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sign_up_modal.html.erb
<div class="modal fade" id="sign_up">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header centered">
        <button class="close" data-dismiss="modal">x</button>
        <h2>sign up</h2>
      </div>

      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>
          <div>
            <%= f.input :username,
                        autofocus: true,
                        label: "USERNAME",
                        label_html: { class: "form-label" } %>
          </div>
          <div>
            <%= f.input :email,
                        label: "EMAIL",
                        label_html: { class: "form-label" } %>
          </div>
          <div>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %>
            <%= f.input :password,
                        autocomplete: "off", 
                        label: "PASSWORD",
                        label_html: { class: "form-label" } %>
          </div>
          <div>
            <%= f.input :password_confirmation,
                        autocomplete: "off",
                        label: "PASSWORD CONFIRMATION",
                        label_html: { class: "form-label" } %>
          </div>
        </div>

        <div class="modal-footer">
          <p>
            <div>
              <%= f.submit "SIGN UP", class: "btn btn-primary" %>
              <a href="#" class="btn btn-primary" data-dismiss="modal">CLOSE</a>
            </div>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_title_bar.html.erb
<div class="col-md-4">
  <h1>
    <%= link_to "showmethebest.xyz", root_path, id: "smtb-logo" %> <small>ALPHA</small>
  </h1>
</div>
<div class="col-md-8">
  <span class="menu-buttons pull-right">
    <% if user_signed_in? %>
      <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "LOGIN", "#login", class: "btn btn-primary", data: { toggle: "modal" } %>
      <%= link_to "SIGN UP", "#sign_up", class: "btn btn-primary", data: { toggle: "modal" } %>
    <% end %>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>showmethebest.xyz</title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="container">
  <%= yield %>
  <%= render "layouts/login_modal" %>
  <%= render "layouts/sign_up_modal" %>
</div>
</body>
</html>